### ISSUE TITLE
Tester l'envoi d'une notification dans l'app

### ISSUE THREAD

**Issue by Yann-Claudon** [Yann-Claudon/Histoire-de-Nos-Villes#9]
Tester l'envoi d'une notification push dans l'application (avec un bouton).

**Comment by MathouLeBrigand** [comment]
Probleme avec Firebase, je veux faire des notifications en Local, mais ca me demande quand meme Firebase

**Comment by MathouLeBrigand** [comment]
j'essaye en Local, mais j'y arrive pas, probleme avec Gradle, j'ai les nerfs
